// Generated by the WOLips Templateengine Plug-in at 19-Sep-2024 4:31:04 pm

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
