// Generated by the WOLips Templateengine Plug-in at 17-Sep-2024 7:42:01 pm


import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
